BACKBONE:
  ANTI_ALIAS: False
  FREEZE_AT: 2
RESNETS:
  DEFORM_INTERVAL: 1
  DEFORM_MODULATED: False
  DEFORM_NUM_GROUPS: 1
  DEFORM_ON_PER_STAGE: [False, False, False, False]
  DEPTH: 50
  NORM: FrozenBN
  NUM_GROUPS: 1
  OUT_FEATURES: ['res3', 'res4', 'res5']
  RES2_OUT_CHANNELS: 256
  RES5_DILATION: 1
  STEM_OUT_CHANNELS: 64
  STRIDE_IN_1X1: True
  WIDTH_PER_GROUP: 64
FPN:
  FUSE_TYPE: sum
  IN_FEATURES: ['res3', 'res4', 'res5']
  NORM: ""
  OUT_CHANNELS: 256
TOP_MODULE:
  DIM: 16
  NAME: conv
MODEL:
  MOBILENET: False
  PIXEL_MEAN: [103.53, 116.28, 123.675]
  FPN_STRIDES: [8, 16, 32, 64, 128]
  INFERENCE_TH_TEST: 0.05
  INFERENCE_TH_TRAIN: 0.05
  IN_FEATURES: ['p3', 'p4', 'p5', 'p6', 'p7']
  NUM_CLASS: 1
  NMS_TH: 0.6
  NORM: GN
  NUM_BOX_CONVS: 4
  NUM_CLASSES: 1
  NUM_CLS_CONVS: 4
  NUM_SHARE_CONVS: 0
  POST_NMS_TOPK_TEST: 100
  POST_NMS_TOPK_TRAIN: 100
  POS_RADIUS: 1.5
  PRE_NMS_TOPK_TEST: 1000
  PRE_NMS_TOPK_TRAIN: 1000
  PRIOR_PROB: 0.01
  SIZES_OF_INTEREST: [64, 128, 256, 512]
  THRESH_WITH_CTR: False
  TOP_LEVELS: 2
  USE_DEFORMABLE: False
  USE_SCALE: True
  YIELD_PROPOSAL: False
LOSS:
  CENTER_SAMPLE: True
  LOSS_ALPHA: 0.25
  LOSS_GAMMA: 2.0
  LOC_LOSS_TYPE: giou