MODEL:
  FPN_STRIDES: [8, 16, 32, 64, 128]
  INFERENCE_TH_TEST: 0.05
  INFERENCE_TH_TRAIN: 0.05
  IN_FEATURES: ['p3', 'p4', 'p5', 'p6', 'p7']
  NUM_CLASS: 1
  NMS_TH: 0.6
  NORM: GN
  NUM_BOX_CONVS: 4
  NUM_CLASSES: 1
  NUM_CLS_CONVS: 4
  NUM_SHARE_CONVS: 0
  POST_NMS_TOPK_TEST: 100
  POST_NMS_TOPK_TRAIN: 100
  POS_RADIUS: 1.5
  PRE_NMS_TOPK_TEST: 1000
  PRE_NMS_TOPK_TRAIN: 1000
  PRIOR_PROB: 0.01
  SIZES_OF_INTEREST: [64, 128, 256, 512]
  THRESH_WITH_CTR: False
  USE_DEFORMABLE: False
  USE_SCALE: True
  YIELD_PROPOSAL: False
LOSS:
  CENTER_SAMPLE: True
  LOSS_ALPHA: 0.25
  LOSS_GAMMA: 2.0
  LOC_LOSS_TYPE: giou