MODEL:
  FPN_STRIDES: [8, 16, 32, 64, 128]
  NUM_CLASS: 1
  NORM: GN
  NUM_BOX_CONVS: 4
  NUM_CLASSES: 1
  NUM_CLS_CONVS: 4
  NUM_SHARE_CONVS: 0
  PRIOR_PROB: 0.01
  USE_DEFORMABLE: False
  USE_SCALE: True

