root_path:
  image_path: "/home/shizai/data2/ocr_data/icdar2015/train/"
  eval_path: "/home/shizai/data2/ocr_data/china_life_test_data"
  weight: "./weights/"
  pretrained_model: ""
  result_dir: "images_result/"
  model_path: "./weights/DB_final.pth"
data:
  process:
    - type: IaaAugment
      args:
        - type: Fliplr
          args:
            p: 0.5
        - type: Affine
          args:
            rotate: [-10,10]
        - type: Resize
          args:
            size: [0.5,3]
    - type: EastRandomCropData
      args:
        size:
          - 640
          - 640
        max_tries: 50
        keep_ratio: True
    - type: MakeBorderMap
      args:
        shrink_ratio: 0.4
    - type: MakeShrinkMap
      args:
        shrink_ratio: 0.4
        min_text_size: 8
  transforms:
    - type: ToTensor
      args: {}
    - type: Normalize
      args:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
  filter_keys: ['img_path', 'img_name', 'text_polys', 'texts', 'ignore_tags', 'shape', 'img']
  ignore_tags: ['*', '###']
model_define:
pretrained:
  pretrained_backbone: True
  pretrained_model: False
train_params:
  batch_size: 16
  epochs: 1200
  lr: 1.0e-3
  workers: 32
  DateParallel: False
inference_params:
  polygon: False
  short_size: 736
  thresh: 0.25
  box_thresh: 0.1
  max_candidates: 1000
  unclip_ratio: 1.5




